profile=high-quality
interpolation
ytdl-format="bestvideo[height<=?1080]+bestaudio/best"

background-color='#282828'
osd-back-color='#3c3836'
osd-border-color='#928374'
osd-color='#ebdbb2'
osd-shadow-color='#1d2021'

script-opts-append=stats-border_color=36383c
script-opts-append=stats-font_color=b2dbeb
script-opts-append=stats-plot_bg_border_color=646f7c
script-opts-append=stats-plot_bg_color=282828
script-opts-append=stats-plot_color=6a9d68

script-opts-append=uosc-color=foreground=689d6a,foreground_text=fbf1c7,background=282828,background_text=ebdbb2,curtain=1d2021,success=8ec07c,error=cc241d
