set -g status-bg "#24273a"
set -g status-fg "#cad3f5"

set -g status-style 'bg=#24273a fg=#cad3f5'
set -g status-left ''

set -g status-right '#[fg=#5b6078,bg=#24273a]#[fg=#cad3f5,bg=#5b6078] %d/%m #[fg=#8aadf4,bg=#5b6078]#[fg=#24273a,bg=#8aadf4] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-style 'fg=#181926 bg=#a6da95 bold'
setw -g window-status-current-format ' #I#[fg=#494d64]:#[fg=#181926]#W#[fg=#181926]#F #[fg=#a6da95,bg=#24273a]'

setw -g window-status-style 'fg=#cad3f5 bg=#494d64'
setw -g window-status-format ' #I#[fg=#cad3f5]:#[fg=#cad3f5]#W#[fg=#cad3f5]#F '
