source-file ~/.config/tmux/themes/.matugen.conf
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",foot:RGB"

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g mouse on 
set -g history-limit 5000 
setw -g mode-keys vi
set -s escape-time 0
