set $hex_background #282828
set $hex_text #ebdbb2
set $hex_dtext #a89984
set $hex_focused #8ec07c
set $hex_unfocused #3c3836
set $hex_active #458588
set $hex_inactive #504945
set $hex_urgent #cc241d
set $hex_placeholder #282828
